%YAML 1.3
---
- Key: [Mouse Gesture Button, pressed]
- KeyPress:
  - minus
  - click
...
---
- Key: [Snipping Tool, pressed]
- KeyPress:
  - Print
  - click
...
---
- Key: [Smart Shift, pressed]
- KeyPress:
  - equal
  - click
...
